### ISSUE TITLE
module declared asynks/asynks

### ISSUE THREAD

**Issue by Merith-TK** [hadihammurabi/asynks#2]
unusable with golang as of this issue
```
$ go get github.com/hadihammurabi/asynks
go: github.com/hadihammurabi/asynks@v0.0.0-20220302031614-41e1b79eb8a1: parsing go.mod:
        module declares its path as: github.com/asynks/asynks
                but was required as: github.com/hadihammurabi/asynks
```

**Comment by hadihammurabi** [comment]
Hi, @Merith-TK.

It should moved to new repository and decoupled from my personal account, asynks/asynks.

**Comment by Merith-TK** [comment]
You need to rename it in `go.mod`
https://github.com/hadihammurabi/asynks/blob/master/go.mod#L1

**Comment by hadihammurabi** [comment]
> You need to rename it in `go.mod` https://github.com/hadihammurabi/asynks/blob/master/go.mod#L1

yesss, thank you.
